name: Playwright Tests
on:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:
     inputs:
        environment:
          type: choice
          description: 'Select Environment'
          options:
          - STG
          - PRD
jobs:
  E2E_Test:
    timeout-minutes: 60
    runs-on: self-hosted
    env:
      WITHOUT_REPORT: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run test

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30
